version: '3.7'
services:
   backend:
      build: backend
      container_name: backend
      ports:
         - 8001:8001
      volumes:
         - ./backend:/app

   frontend:
      build: frontend
      container_name: frontend
      ports:
         - 8000:8000
      depends_on:
         - backend
      volumes:
         - ./frontend:/app

   memcached:
      image: memcached
      container_name: memcached
      ports:
         - 11211:11211